export type Lang = "en" | "es";

const en = {
  "quiet.because": "Quiet because: {name}",
  "quiet.on": "Quiet mode on",
  "quiet.off": "Quiet mode off",
  "restore.airdrop": "Restore AirDrop now",
  "airdrop.break": "Allow AirDrop for 2 min",
  "pause.automation": "Pause automation",
  "resume.automation": "Resume automation",
  "note.scan-before": "A Wi-Fi scan was logged {ms} ms before this cut",
  "note.scan-during": "A Wi-Fi scan was logged {ms} ms into this cut",
  "note.awdl-before": "AWDL activity was logged {ms} ms before this cut",
  "note.awdl-during": "AWDL activity was logged {ms} ms into this cut",
  "note.channel-change": "The Wi-Fi channel changed near this cut",
  "note.none": "No logged Wi-Fi event near this cut",
  "lease.manual": "Manual",
  "lease.timed": "Timed ({min} min)",
  "lease.input": "Microphone in use",
  "lease.test": "Quiet test",
  "notify.cut.title": "Wi-Fi interruption",
  "notify.cut.body": "Router probes failed for about {ms} ms during {name}.",
  "notify.restored.title": "AirDrop restored",
  "notify.restored.body": "Quietlink stopped responding, so the warden turned AWDL back on.",
  "notify.privilege.title": "Quiet mode needs permission",
  "notify.privilege.body": "Open Quietlink Settings → Privileges to install the AWDL rule.",
  "notify.band.title": "Connected on {band} GHz",
  "notify.band.body": "You've connected on 6 GHz on this network before. Reconnecting may bring it back.",
  "notify.session.title": "Session ended with interruptions",
  "notify.session.body": "{count} interruption(s) during {name}.",
  "ui.quiet": "Quiet",
  "ui.off": "Off",
  "ui.fault": "Needs attention",
  "ui.suppressed": "AirDrop restored — automation stopped",
  "ui.grace": "Ending in a few seconds",
  "ui.break": "AirDrop allowed",
  "ui.activating": "Turning on…",
  "ui.restoring": "Turning off…",
  "ui.quietNow": "Quiet now",
  "ui.stop": "Stop",
  "ui.for30": "30 min",
  "ui.for60": "1 h",
  "ui.for120": "2 h",
  "ui.untilOff": "Until off",
  "ui.reenable": "Re-enable automation",
  "ui.router": "Router",
  "ui.internet": "Internet",
  "ui.jitter": "Jitter",
  "ui.loss": "Loss",
  "ui.provisional": "(provisional)",
  "ui.late": "{n} late replies",
  "ui.wifi": "Wi-Fi",
  "ui.notConnected": "Not on Wi-Fi — monitoring paused",
  "ui.channel": "ch {n}",
  "ui.phy": "PHY {n} Mbps",
  "ui.reconnect": "Reconnect Wi-Fi",
  "ui.reconnectConfirm": "Wi-Fi drops for a few seconds. Continue?",
  "ui.reconnectBlocked": "Not available while quiet mode is on",
  "ui.reconnecting": "Reconnecting…",
  "ui.reconnectDone": "Reconnected",
  "ui.events": "Recent interruptions",
  "ui.noEvents": "No interruptions in the last hour",
  "ui.lastHour": "{n} in the last hour",
  "ui.test": "Quiet test",
  "ui.testStart": "Run quiet test (4 min)",
  "ui.testCancel": "Cancel test",
  "ui.testRunning": "Block {n} of 4 · {cond}",
  "ui.testArming": "Preparing block {n} of 4…",
  "ui.testA": "baseline",
  "ui.testB": "quiet mode",
  "ui.testHint": "Don't use AirDrop during the test.",
  "ui.testResult": "Baseline: {a} spikes >{ms} ms in {as} probes · Quiet mode: {b} in {bs}",
  "ui.testInvalid": "Test stopped: {reason}",
  "ui.testCancelled": "Test cancelled",
  "ui.settings": "Settings",
  "ui.quit": "Quit",
  "ui.privilegeMissing": "Quiet mode needs a one-time permission.",
  "ui.installPrivilege": "Install permission…",
  "ui.wardenDown": "Background service not responding",
  "ui.recovering": "Restoring previous state…",
  "ui.probesBlocked": "All probes are failing while Wi-Fi is up. A firewall (LuLu, Little Snitch) may be blocking quietlink-helper.",
  "ui.paused": "Automation paused",
  "ui.sessions": "Sessions",
  "ui.noSessions": "No sessions yet",
  "ui.sessionLine": "{dur} min · p95 {p95} ms · {cuts} cuts · loss {loss} %",
  "set.title": "Quietlink Settings",
  "set.triggers": "Triggers",
  "set.monitor": "Monitor",
  "set.privileges": "Permissions",
  "set.data": "Data",
  "set.about": "About",
  "set.presets": "Apps",
  "set.verified": "verified",
  "set.unverified": "not yet verified",
  "set.showUnverified": "Show unverified presets",
  "set.noVerified": "No presets are verified on this Mac yet. Show unverified presets to see them, or add a running app.",
  "set.addApp": "Add running app…",
  "set.thisExe": "This executable only",
  "set.wholeApp": "Whole application",
  "set.remove": "Remove",
  "set.input": "Quiet while an input device is running",
  "set.inputHint": "Heuristic: catches browser calls, but any app using the microphone — or a headset playing audio — can trigger it.",
  "set.grace": "Grace period after a trigger ends: {n} s",
  "set.external": "External probe target",
  "set.externalHint": "Continuous pings go to this host (a third party). Leave empty to disable.",
  "set.extra": "Extra hops (e.g. mesh nodes), comma-separated",
  "set.menuPing": "Show router ping in the menu bar",
  "set.explain": "Explain cuts (experimental)",
  "set.explainHint": "Reads a narrow slice of the system Wi-Fi log to note scans or AWDL activity near a cut. Coincidence, not cause.",
  "set.privStatus": "Status",
  "set.privInstalled": "Installed",
  "set.privMissing": "Not installed",
  "set.wardenRunning": "Background service running",
  "set.privExplain": "Quietlink installs a sudoers rule that lets your account run exactly two commands without a password: /sbin/ifconfig awdl0 down and /sbin/ifconfig awdl0 up. Any process running as you can also run those two commands. A background service (the warden) is the only part of Quietlink that runs them, and it turns AWDL back on if the app stops responding.",
  "set.install": "Install",
  "set.uninstall": "Uninstall",
  "set.retention": "Per-second samples and events are kept 24 h, sessions 30 days. Nothing leaves this Mac except the probes.",
  "set.clear": "Clear all data",
  "set.cleared": "Cleared",
  "set.export": "Export diagnostics",
  "set.includeIds": "Include identifiers (IP addresses, paths)",
  "set.exported": "Saved to {path}",
  "set.cli": "Install command-line tool",
  "set.cliDone": "Installed at {path}",
  "set.login": "Open at login",
  "set.lang": "Language",
  "set.support": "Verified on macOS 27 (Apple Silicon). Other versions may work but are untested.",
  "set.license": "MIT License",
  "set.working": "Working…",
  "set.failed": "Failed: {error}",
  "ui.offNote": "AirDrop and Handoff work normally",
  "ui.quietFor": "Quiet for…",
  "ui.toRouter": "to your router, last 5 min",
  "ui.factsLine": "{spikes} spikes over {ms} ms · {lost} lost",
  "ui.cutOf": "Cut of {d}",
  "ui.pauseShort": "Pause",
  "set.menuTraffic": "Show current download/upload in the menu bar",
  "ui.traffic": "Traffic",
  "ui.restorePending": "Turning AirDrop back on…",
  "ui.reconnectedOn": "Reconnected on {band} GHz",
  "ui.reconnectTimeout": "Wi-Fi didn't come back within 20 s. Turn Wi-Fi on from the menu bar.",
  "s.triggersLede": "Quiet mode turns on while one of these is running and off again when it closes. AirDrop keeps working the rest of the time.",
  "s.games": "Games",
  "s.calls": "Calls",
  "s.callsNote": "Call apps only count while a microphone is in use, since having them open doesn't mean you're on a call.",
  "s.withMic": "Only while a microphone is in use",
  "s.untested": "Not yet tested on this Mac, may not turn on",
  "s.anyMic": "Any app using a microphone",
  "s.yourApps": "Your apps",
  "s.wholeApp": "Whole app",
  "s.onlyProcess": "One process only",
  "s.addAnother": "Add another app",
  "s.noApps": "Add a game or app that isn't listed",
  "s.addApp": "Add app…",
  "s.after": "When it ends",
  "s.graceTitle": "Wait before turning off",
  "s.graceDetail": "Avoids flickering between matches or loading screens.",
  "s.search": "Search running apps",
  "s.noMatch": "No running app matches.",
  "s.cancel": "Cancel",
  "s.scope": "What to watch",
  "s.wholeAppHint": "Quiet mode turns on whenever any part of this app is running.",
  "s.onlyProcessHint": "Pick the process that only exists while you play, like a match window.",
  "s.back": "Back",
  "s.add": "Add",
  "s.monitorLede": "Quietlink pings your router (and optionally one internet host) to show where lag comes from.",
  "s.menuBar": "Menu bar",
  "s.showPing": "Show ping",
  "s.showPingDetail": "Latency to your router, in milliseconds.",
  "s.showTraffic": "Show upload and download",
  "s.showTrafficDetail": "What your Mac is sending and receiving right now, in Mb/s. Not your line's maximum speed.",
  "s.probes": "Where to ping",
  "s.external": "Internet host",
  "s.externalDetail": "Separates Wi-Fi problems from internet problems.",
  "s.invalidIp": "Enter an IPv4 address like 1.1.1.1, or leave it empty.",
  "s.hops": "Extra devices",
  "s.hopsDetail": "Mesh nodes or access points to watch too.",
  "s.explainTitle": "Explanations",
  "s.privLede": "Turning AirDrop's radio off needs administrator rights. Quietlink asks once and then never needs your password again.",
  "s.privReady": "Quiet mode is ready",
  "s.privReadyDetail": "The background helper is running and can restore AirDrop at any time.",
  "s.wardenStarting": "Starting the background helper…",
  "s.privNeeded": "Quiet mode needs your permission",
  "s.privNeededDetail": "You'll be asked for your Mac password once.",
  "s.allow": "Allow…",
  "s.remove": "Remove",
  "s.cancelled": "Cancelled.",
  "s.allows": "What this allows",
  "s.allowOff": "Turn AirDrop's radio off",
  "s.allowOffDetail": "While a game or call is running.",
  "s.allowOn": "Turn it back on",
  "s.allowOnDetail": "As soon as you're done, or if Quietlink stops responding.",
  "s.safety": "Nothing else",
  "s.safetyDetail": "No other system settings, files or network access.",
  "s.allowsNote": "Other apps running under your account could also turn AirDrop off or on. They can't do anything else with this permission.",
  "s.showDetails": "Show technical details",
  "s.hideDetails": "Hide technical details",
  "s.techDetail": "Quietlink adds this rule to /etc/sudoers.d, checked with visudo. Removing the permission deletes it.",
  "s.cuts": "cuts",
  "s.sessionsHint": "A session is saved each time quiet mode runs for a game or call.",
  "s.share": "Share and tools",
  "s.exportDetail": "A Markdown report in your Downloads folder, useful when asking for help.",
  "s.exportBtn": "Export",
  "s.includeIdsDetail": "Off: IP addresses, user name and paths are replaced.",
  "s.cliTitle": "Command-line tool",
  "s.cliDetail": "Control Quietlink from Terminal with quietlink on / off / status.",
  "s.install": "Install",
  "s.clearDetail": "Deletes measurements, sessions and network history from this Mac.",
  "s.clear": "Clear…",
  "s.confirmClear": "Click again to clear",
  "s.tagline": "Wi-Fi without lag spikes while you play or call.",
  "s.general": "General",
  "s.version": "Version",
  "s.license": "License",
  "ui.reconnectConfirmShort": "Wi-Fi drops briefly — click again",
  "s.untestedTag": "Untested",
  "s.untestedNote": "Untested entries haven't been checked on this Mac yet and may not turn quiet mode on.",
  "s.checkNow": "Check now",
  "s.download": "Download {v}",
  "s.downloadShort": "Download",
  "s.updateAvailable": "Quietlink {v} is available.",
  "s.checking": "Checking for updates…",
  "s.upToDate": "You have the latest version.",
  "s.checkFailed": "Couldn't reach GitHub. Try again later.",
  "s.autoCheck": "Check for updates automatically",
  "s.autoCheckDetail": "Once a day, Quietlink asks GitHub for the latest release. Nothing else is sent.",
  "s.installUpdate": "Install {v} and restart",
  "s.installShort": "Install",
  "s.installing": "Downloading and checking…",
  "s.restarting": "Restarting…",
  "s.installFailed": "The update couldn't be installed ({error}). Your current version is untouched.",
};

export type Key = keyof typeof en;

const es: Record<Key, string> = {
  "quiet.because": "Silencio por: {name}",
  "quiet.on": "Modo silencio activado",
  "quiet.off": "Modo silencio desactivado",
  "restore.airdrop": "Restaurar AirDrop ahora",
  "airdrop.break": "Permitir AirDrop 2 min",
  "pause.automation": "Pausar automatización",
  "resume.automation": "Reanudar automatización",
  "note.scan-before": "Se registró un escaneo Wi-Fi {ms} ms antes de este corte",
  "note.scan-during": "Se registró un escaneo Wi-Fi {ms} ms después de empezar este corte",
  "note.awdl-before": "Se registró actividad AWDL {ms} ms antes de este corte",
  "note.awdl-during": "Se registró actividad AWDL {ms} ms después de empezar este corte",
  "note.channel-change": "El canal Wi-Fi cambió cerca de este corte",
  "note.none": "Ningún evento Wi-Fi registrado cerca de este corte",
  "lease.manual": "Manual",
  "lease.timed": "Temporizado ({min} min)",
  "lease.input": "Micrófono en uso",
  "lease.test": "Quiet test",
  "notify.cut.title": "Interrupción Wi-Fi",
  "notify.cut.body": "Los pings al router fallaron unos {ms} ms durante {name}.",
  "notify.restored.title": "AirDrop restaurado",
  "notify.restored.body": "Quietlink dejó de responder y el warden volvió a activar AWDL.",
  "notify.privilege.title": "El modo silencio necesita permiso",
  "notify.privilege.body": "Abre Ajustes de Quietlink → Permisos para instalar la regla de AWDL.",
  "notify.band.title": "Conectado en {band} GHz",
  "notify.band.body": "Ya te has conectado a 6 GHz en esta red. Reconectar puede recuperarlo.",
  "notify.session.title": "Sesión terminada con cortes",
  "notify.session.body": "{count} corte(s) durante {name}.",
  "ui.quiet": "Silencio",
  "ui.off": "Apagado",
  "ui.fault": "Requiere atención",
  "ui.suppressed": "AirDrop restaurado — automatización detenida",
  "ui.grace": "Terminando en unos segundos",
  "ui.break": "AirDrop permitido",
  "ui.activating": "Activando…",
  "ui.restoring": "Desactivando…",
  "ui.quietNow": "Silenciar ahora",
  "ui.stop": "Parar",
  "ui.for30": "30 min",
  "ui.for60": "1 h",
  "ui.for120": "2 h",
  "ui.untilOff": "Hasta apagar",
  "ui.reenable": "Reactivar automatización",
  "ui.router": "Router",
  "ui.internet": "Internet",
  "ui.jitter": "Jitter",
  "ui.loss": "Pérdida",
  "ui.provisional": "(provisional)",
  "ui.late": "{n} respuestas tardías",
  "ui.wifi": "Wi-Fi",
  "ui.notConnected": "Sin Wi-Fi — monitor en pausa",
  "ui.channel": "canal {n}",
  "ui.phy": "PHY {n} Mbps",
  "ui.reconnect": "Reconectar Wi-Fi",
  "ui.reconnectConfirm": "El Wi-Fi se corta unos segundos. ¿Continuar?",
  "ui.reconnectBlocked": "No disponible con el modo silencio activo",
  "ui.reconnecting": "Reconectando…",
  "ui.reconnectDone": "Reconectado",
  "ui.events": "Cortes recientes",
  "ui.noEvents": "Sin cortes en la última hora",
  "ui.lastHour": "{n} en la última hora",
  "ui.test": "Quiet test",
  "ui.testStart": "Ejecutar quiet test (4 min)",
  "ui.testCancel": "Cancelar test",
  "ui.testRunning": "Bloque {n} de 4 · {cond}",
  "ui.testArming": "Preparando bloque {n} de 4…",
  "ui.testA": "referencia",
  "ui.testB": "modo silencio",
  "ui.testHint": "No uses AirDrop durante el test.",
  "ui.testResult": "Referencia: {a} picos >{ms} ms en {as} pings · Modo silencio: {b} en {bs}",
  "ui.testInvalid": "Test detenido: {reason}",
  "ui.testCancelled": "Test cancelado",
  "ui.settings": "Ajustes",
  "ui.quit": "Salir",
  "ui.privilegeMissing": "El modo silencio necesita un permiso (una sola vez).",
  "ui.installPrivilege": "Instalar permiso…",
  "ui.wardenDown": "El servicio en segundo plano no responde",
  "ui.recovering": "Restaurando el estado anterior…",
  "ui.probesBlocked": "Todos los pings fallan con el Wi-Fi activo. Un cortafuegos (LuLu, Little Snitch) puede estar bloqueando quietlink-helper.",
  "ui.paused": "Automatización en pausa",
  "ui.sessions": "Sesiones",
  "ui.noSessions": "Aún no hay sesiones",
  "ui.sessionLine": "{dur} min · p95 {p95} ms · {cuts} cortes · pérdida {loss} %",
  "set.title": "Ajustes de Quietlink",
  "set.triggers": "Disparadores",
  "set.monitor": "Monitor",
  "set.privileges": "Permisos",
  "set.data": "Datos",
  "set.about": "Acerca de",
  "set.presets": "Apps",
  "set.verified": "verificado",
  "set.unverified": "sin verificar",
  "set.showUnverified": "Mostrar presets sin verificar",
  "set.noVerified": "Aún no hay presets verificados en este Mac. Muestra los no verificados para verlos, o añade una app abierta.",
  "set.addApp": "Añadir app abierta…",
  "set.thisExe": "Solo este ejecutable",
  "set.wholeApp": "Toda la aplicación",
  "set.remove": "Quitar",
  "set.input": "Silenciar mientras un dispositivo de entrada esté activo",
  "set.inputHint": "Heurística: detecta llamadas en el navegador, pero cualquier app que use el micrófono — o unos cascos reproduciendo audio — puede activarlo.",
  "set.grace": "Margen tras terminar un disparador: {n} s",
  "set.external": "Destino externo de pings",
  "set.externalHint": "Pings continuos a este host (un tercero). Déjalo vacío para desactivarlo.",
  "set.extra": "Saltos extra (p. ej. nodos mesh), separados por comas",
  "set.menuPing": "Mostrar ping del router en la barra de menús",
  "set.explain": "Explicar cortes (experimental)",
  "set.explainHint": "Lee una parte acotada del log Wi-Fi del sistema para anotar escaneos o actividad AWDL cerca de un corte. Coincidencia, no causa.",
  "set.privStatus": "Estado",
  "set.privInstalled": "Instalado",
  "set.privMissing": "No instalado",
  "set.wardenRunning": "Servicio en segundo plano activo",
  "set.privExplain": "Quietlink instala una regla de sudoers que permite a tu cuenta ejecutar exactamente dos comandos sin contraseña: /sbin/ifconfig awdl0 down y /sbin/ifconfig awdl0 up. Cualquier proceso que se ejecute como tú también puede ejecutarlos. Un servicio en segundo plano (el warden) es la única parte de Quietlink que los ejecuta, y vuelve a activar AWDL si la app deja de responder.",
  "set.install": "Instalar",
  "set.uninstall": "Desinstalar",
  "set.retention": "Las muestras por segundo y los eventos se guardan 24 h; las sesiones, 30 días. Nada sale de este Mac salvo los pings.",
  "set.clear": "Borrar todos los datos",
  "set.cleared": "Borrado",
  "set.export": "Exportar diagnóstico",
  "set.includeIds": "Incluir identificadores (IPs, rutas)",
  "set.exported": "Guardado en {path}",
  "set.cli": "Instalar herramienta de línea de comandos",
  "set.cliDone": "Instalada en {path}",
  "set.login": "Abrir al iniciar sesión",
  "set.lang": "Idioma",
  "set.support": "Verificado en macOS 27 (Apple Silicon). Otras versiones pueden funcionar pero no están probadas.",
  "set.license": "Licencia MIT",
  "set.working": "Trabajando…",
  "set.failed": "Error: {error}",
  "ui.offNote": "AirDrop y Handoff funcionan con normalidad",
  "ui.quietFor": "Silenciar durante…",
  "ui.toRouter": "al router, últimos 5 min",
  "ui.factsLine": "{spikes} picos de más de {ms} ms · {lost} perdidos",
  "ui.cutOf": "Corte de {d}",
  "ui.pauseShort": "Pausar",
  "set.menuTraffic": "Mostrar bajada/subida actual en la barra de menús",
  "ui.traffic": "Tráfico",
  "ui.restorePending": "Volviendo a activar AirDrop…",
  "ui.reconnectedOn": "Reconectado en {band} GHz",
  "ui.reconnectTimeout": "El Wi-Fi no volvió en 20 s. Actívalo desde la barra de menús.",
  "s.triggersLede": "El modo silencio se activa mientras alguno de estos está abierto y se desactiva al cerrarlo. AirDrop funciona el resto del tiempo.",
  "s.games": "Juegos",
  "s.calls": "Llamadas",
  "s.callsNote": "Las apps de llamadas solo cuentan mientras hay un micrófono en uso: tenerlas abiertas no significa que estés en una llamada.",
  "s.withMic": "Solo con un micrófono en uso",
  "s.untested": "Aún sin probar en este Mac, puede no activarse",
  "s.anyMic": "Cualquier app usando un micrófono",
  "s.yourApps": "Tus apps",
  "s.wholeApp": "App completa",
  "s.onlyProcess": "Solo un proceso",
  "s.addAnother": "Añadir otra app",
  "s.noApps": "Añade un juego o app que no esté en la lista",
  "s.addApp": "Añadir app…",
  "s.after": "Al terminar",
  "s.graceTitle": "Esperar antes de desactivar",
  "s.graceDetail": "Evita parpadeos entre partidas o pantallas de carga.",
  "s.search": "Buscar apps abiertas",
  "s.noMatch": "Ninguna app abierta coincide.",
  "s.cancel": "Cancelar",
  "s.scope": "Qué vigilar",
  "s.wholeAppHint": "El modo silencio se activa siempre que cualquier parte de esta app esté abierta.",
  "s.onlyProcessHint": "Elige el proceso que solo existe mientras juegas, como la ventana de partida.",
  "s.back": "Atrás",
  "s.add": "Añadir",
  "s.monitorLede": "Quietlink hace ping a tu router (y opcionalmente a un host de internet) para mostrar de dónde viene el lag.",
  "s.menuBar": "Barra de menús",
  "s.showPing": "Mostrar ping",
  "s.showPingDetail": "Latencia al router, en milisegundos.",
  "s.showTraffic": "Mostrar subida y bajada",
  "s.showTrafficDetail": "Lo que tu Mac envía y recibe ahora mismo, en Mb/s. No es la velocidad máxima de tu línea.",
  "s.probes": "A dónde hacer ping",
  "s.external": "Host de internet",
  "s.externalDetail": "Separa problemas del Wi-Fi de problemas de internet.",
  "s.invalidIp": "Escribe una IPv4 como 1.1.1.1, o déjalo vacío.",
  "s.hops": "Dispositivos extra",
  "s.hopsDetail": "Nodos mesh o puntos de acceso a vigilar también.",
  "s.explainTitle": "Explicaciones",
  "s.privLede": "Apagar la radio de AirDrop requiere permisos de administrador. Quietlink lo pide una vez y no vuelve a necesitar tu contraseña.",
  "s.privReady": "El modo silencio está listo",
  "s.privReadyDetail": "El ayudante en segundo plano está activo y puede restaurar AirDrop en cualquier momento.",
  "s.wardenStarting": "Iniciando el ayudante en segundo plano…",
  "s.privNeeded": "El modo silencio necesita tu permiso",
  "s.privNeededDetail": "Se te pedirá la contraseña del Mac una sola vez.",
  "s.allow": "Permitir…",
  "s.remove": "Quitar",
  "s.cancelled": "Cancelado.",
  "s.allows": "Qué permite",
  "s.allowOff": "Apagar la radio de AirDrop",
  "s.allowOffDetail": "Mientras hay un juego o llamada abiertos.",
  "s.allowOn": "Volver a encenderla",
  "s.allowOnDetail": "En cuanto terminas, o si Quietlink deja de responder.",
  "s.safety": "Nada más",
  "s.safetyDetail": "Ningún otro ajuste del sistema, archivo ni acceso a red.",
  "s.allowsNote": "Otras apps de tu cuenta también podrían apagar o encender AirDrop. No pueden hacer nada más con este permiso.",
  "s.showDetails": "Ver detalles técnicos",
  "s.hideDetails": "Ocultar detalles técnicos",
  "s.techDetail": "Quietlink añade esta regla a /etc/sudoers.d, validada con visudo. Quitar el permiso la borra.",
  "s.cuts": "cortes",
  "s.sessionsHint": "Se guarda una sesión cada vez que el modo silencio se activa por un juego o llamada.",
  "s.share": "Compartir y herramientas",
  "s.exportDetail": "Un informe Markdown en Descargas, útil para pedir ayuda.",
  "s.exportBtn": "Exportar",
  "s.includeIdsDetail": "Desactivado: se ocultan IPs, usuario y rutas.",
  "s.cliTitle": "Herramienta de terminal",
  "s.cliDetail": "Controla Quietlink desde Terminal con quietlink on / off / status.",
  "s.install": "Instalar",
  "s.clearDetail": "Borra medidas, sesiones e historial de redes de este Mac.",
  "s.clear": "Borrar…",
  "s.confirmClear": "Pulsa otra vez para borrar",
  "s.tagline": "Wi-Fi sin picos de lag mientras juegas o llamas.",
  "s.general": "General",
  "s.version": "Versión",
  "s.license": "Licencia",
  "ui.reconnectConfirmShort": "El Wi-Fi se corta un momento — pulsa otra vez",
  "s.untestedTag": "Sin probar",
  "s.untestedNote": "Las entradas sin probar aún no se han comprobado en este Mac y pueden no activar el modo silencio.",
  "s.checkNow": "Buscar ahora",
  "s.download": "Descargar {v}",
  "s.downloadShort": "Descargar",
  "s.updateAvailable": "Quietlink {v} está disponible.",
  "s.checking": "Buscando actualizaciones…",
  "s.upToDate": "Tienes la última versión.",
  "s.checkFailed": "No se pudo contactar con GitHub. Prueba más tarde.",
  "s.autoCheck": "Buscar actualizaciones automáticamente",
  "s.autoCheckDetail": "Una vez al día, Quietlink pregunta a GitHub cuál es la última versión. No se envía nada más.",
  "s.installUpdate": "Instalar {v} y reiniciar",
  "s.installShort": "Instalar",
  "s.installing": "Descargando y comprobando…",
  "s.restarting": "Reiniciando…",
  "s.installFailed": "No se pudo instalar la actualización ({error}). Tu versión actual sigue intacta.",
};

export const strings: Record<Lang, Record<Key, string>> = { en, es };

export function t(lang: Lang, key: Key, vars: Record<string, string | number> = {}): string {
  return strings[lang][key].replace(/\{(\w+)\}/g, (m, name) => (name in vars ? String(vars[name]) : m));
}
