export type Lang = "en" | "es";

const en = {
  "quiet.because": "Quiet because: {name}",
  "quiet.on": "Quiet mode on",
  "quiet.off": "Quiet mode off",
  "restore.airdrop": "Restore AirDrop now",
  "airdrop.break": "Allow AirDrop for 2 min",
  "pause.automation": "Pause automation",
  "resume.automation": "Resume automation",
  "note.scan-before": "A Wi-Fi scan was logged {ms} ms before this cut",
  "note.scan-during": "A Wi-Fi scan was logged {ms} ms into this cut",
  "note.awdl-before": "AWDL activity was logged {ms} ms before this cut",
  "note.awdl-during": "AWDL activity was logged {ms} ms into this cut",
  "note.channel-change": "The Wi-Fi channel changed near this cut",
  "note.none": "No logged Wi-Fi event near this cut",
  "lease.manual": "Manual",
  "lease.timed": "Timed ({min} min)",
  "lease.input": "Microphone in use",
  "lease.test": "Quiet test",
  "notify.cut.title": "Wi-Fi interruption",
  "notify.cut.body": "Router probes failed for about {ms} ms during {name}.",
  "notify.restored.title": "AirDrop restored",
  "notify.restored.body": "Quietlink stopped responding, so the warden turned AWDL back on.",
  "notify.privilege.title": "Quiet mode needs permission",
  "notify.privilege.body": "Open Quietlink Settings → Privileges to install the AWDL rule.",
  "notify.band.title": "Connected on {band} GHz",
  "notify.band.body": "You've connected on 6 GHz on this network before. Reconnecting may bring it back.",
  "notify.session.title": "Session ended with interruptions",
  "notify.session.body": "{count} interruption(s) during {name}.",
  "ui.quiet": "Quiet",
  "ui.off": "Off",
  "ui.fault": "Needs attention",
  "ui.suppressed": "AirDrop restored — automation stopped",
  "ui.grace": "Ending in a few seconds",
  "ui.break": "AirDrop allowed",
  "ui.activating": "Turning on…",
  "ui.restoring": "Turning off…",
  "ui.quietNow": "Quiet now",
  "ui.stop": "Stop",
  "ui.for30": "30 min",
  "ui.for60": "1 h",
  "ui.for120": "2 h",
  "ui.untilOff": "Until off",
  "ui.reenable": "Re-enable automation",
  "ui.router": "Router",
  "ui.internet": "Internet",
  "ui.jitter": "Jitter",
  "ui.loss": "Loss",
  "ui.provisional": "(provisional)",
  "ui.late": "{n} late replies",
  "ui.wifi": "Wi-Fi",
  "ui.notConnected": "Not on Wi-Fi — monitoring paused",
  "ui.channel": "ch {n}",
  "ui.phy": "PHY {n} Mbps",
  "ui.reconnect": "Reconnect Wi-Fi",
  "ui.reconnectConfirm": "Wi-Fi drops for a few seconds. Continue?",
  "ui.reconnectBlocked": "Not available while quiet mode is on",
  "ui.reconnecting": "Reconnecting…",
  "ui.reconnectDone": "Reconnected",
  "ui.events": "Recent interruptions",
  "ui.noEvents": "No interruptions in the last hour",
  "ui.lastHour": "{n} in the last hour",
  "ui.test": "Quiet test",
  "ui.testStart": "Run quiet test (4 min)",
  "ui.testCancel": "Cancel test",
  "ui.testRunning": "Block {n} of 4 · {cond}",
  "ui.testArming": "Preparing block {n} of 4…",
  "ui.testA": "baseline",
  "ui.testB": "quiet mode",
  "ui.testHint": "Don't use AirDrop during the test.",
  "ui.testResult": "Baseline: {a} spikes >{ms} ms in {as} probes · Quiet mode: {b} in {bs}",
  "ui.testInvalid": "Test stopped: {reason}",
  "ui.testCancelled": "Test cancelled",
  "ui.settings": "Settings",
  "ui.quit": "Quit",
  "ui.privilegeMissing": "Quiet mode needs a one-time permission.",
  "ui.installPrivilege": "Install permission…",
  "ui.wardenDown": "Background service not responding",
  "ui.recovering": "Restoring previous state…",
  "ui.probesBlocked": "All probes are failing while Wi-Fi is up. A firewall (LuLu, Little Snitch) may be blocking quietlink-helper.",
  "ui.paused": "Automation paused",
  "ui.sessions": "Sessions",
  "ui.noSessions": "No sessions yet",
  "ui.sessionLine": "{dur} min · p95 {p95} ms · {cuts} cuts · loss {loss} %",
  "set.title": "Quietlink Settings",
  "set.triggers": "Triggers",
  "set.monitor": "Monitor",
  "set.privileges": "Permissions",
  "set.data": "Data",
  "set.about": "About",
  "set.presets": "Apps",
  "set.verified": "verified",
  "set.unverified": "not yet verified",
  "set.showUnverified": "Show unverified presets",
  "set.noVerified": "No presets are verified on this Mac yet. Show unverified presets to see them, or add a running app.",
  "set.addApp": "Add running app…",
  "set.thisExe": "This executable only",
  "set.wholeApp": "Whole application",
  "set.remove": "Remove",
  "set.input": "Quiet while an input device is running",
  "set.inputHint": "Heuristic: catches browser calls, but any app using the microphone — or a headset playing audio — can trigger it.",
  "set.grace": "Grace period after a trigger ends: {n} s",
  "set.external": "External probe target",
  "set.externalHint": "Continuous pings go to this host (a third party). Leave empty to disable.",
  "set.extra": "Extra hops (e.g. mesh nodes), comma-separated",
  "set.menuPing": "Show router ping in the menu bar",
  "set.explain": "Explain cuts (experimental)",
  "set.explainHint": "Reads a narrow slice of the system Wi-Fi log to note scans or AWDL activity near a cut. Coincidence, not cause.",
  "set.privStatus": "Status",
  "set.privInstalled": "Installed",
  "set.privMissing": "Not installed",
  "set.wardenRunning": "Background service running",
  "set.privExplain": "Quietlink installs a sudoers rule that lets your account run exactly two commands without a password: /sbin/ifconfig awdl0 down and /sbin/ifconfig awdl0 up. Any process running as you can also run those two commands. A background service (the warden) is the only part of Quietlink that runs them, and it turns AWDL back on if the app stops responding.",
  "set.install": "Install",
  "set.uninstall": "Uninstall",
  "set.retention": "Per-second samples and events are kept 24 h, sessions 30 days. Nothing leaves this Mac except the probes.",
  "set.clear": "Clear all data",
  "set.cleared": "Cleared",
  "set.export": "Export diagnostics",
  "set.includeIds": "Include identifiers (IP addresses, paths)",
  "set.exported": "Saved to {path}",
  "set.cli": "Install command-line tool",
  "set.cliDone": "Installed at {path}",
  "set.login": "Open at login",
  "set.lang": "Language",
  "set.support": "Verified on macOS 27 (Apple Silicon). Other versions may work but are untested.",
  "set.license": "MIT License",
  "set.working": "Working…",
  "set.failed": "Failed: {error}",
  "ui.offNote": "AirDrop and Handoff work normally",
  "ui.quietFor": "Quiet for…",
  "ui.toRouter": "to your router, last 5 min",
  "ui.factsLine": "{spikes} spikes over {ms} ms · {lost} lost",
  "ui.cutOf": "Cut of {d}",
  "ui.pauseShort": "Pause",
  "set.menuTraffic": "Show current download/upload in the menu bar",
  "ui.traffic": "Traffic",
};

export type Key = keyof typeof en;

const es: Record<Key, string> = {
  "quiet.because": "Silencio por: {name}",
  "quiet.on": "Modo silencio activado",
  "quiet.off": "Modo silencio desactivado",
  "restore.airdrop": "Restaurar AirDrop ahora",
  "airdrop.break": "Permitir AirDrop 2 min",
  "pause.automation": "Pausar automatización",
  "resume.automation": "Reanudar automatización",
  "note.scan-before": "Se registró un escaneo Wi-Fi {ms} ms antes de este corte",
  "note.scan-during": "Se registró un escaneo Wi-Fi {ms} ms después de empezar este corte",
  "note.awdl-before": "Se registró actividad AWDL {ms} ms antes de este corte",
  "note.awdl-during": "Se registró actividad AWDL {ms} ms después de empezar este corte",
  "note.channel-change": "El canal Wi-Fi cambió cerca de este corte",
  "note.none": "Ningún evento Wi-Fi registrado cerca de este corte",
  "lease.manual": "Manual",
  "lease.timed": "Temporizado ({min} min)",
  "lease.input": "Micrófono en uso",
  "lease.test": "Quiet test",
  "notify.cut.title": "Interrupción Wi-Fi",
  "notify.cut.body": "Los pings al router fallaron unos {ms} ms durante {name}.",
  "notify.restored.title": "AirDrop restaurado",
  "notify.restored.body": "Quietlink dejó de responder y el warden volvió a activar AWDL.",
  "notify.privilege.title": "El modo silencio necesita permiso",
  "notify.privilege.body": "Abre Ajustes de Quietlink → Permisos para instalar la regla de AWDL.",
  "notify.band.title": "Conectado en {band} GHz",
  "notify.band.body": "Ya te has conectado a 6 GHz en esta red. Reconectar puede recuperarlo.",
  "notify.session.title": "Sesión terminada con cortes",
  "notify.session.body": "{count} corte(s) durante {name}.",
  "ui.quiet": "Silencio",
  "ui.off": "Apagado",
  "ui.fault": "Requiere atención",
  "ui.suppressed": "AirDrop restaurado — automatización detenida",
  "ui.grace": "Terminando en unos segundos",
  "ui.break": "AirDrop permitido",
  "ui.activating": "Activando…",
  "ui.restoring": "Desactivando…",
  "ui.quietNow": "Silenciar ahora",
  "ui.stop": "Parar",
  "ui.for30": "30 min",
  "ui.for60": "1 h",
  "ui.for120": "2 h",
  "ui.untilOff": "Hasta apagar",
  "ui.reenable": "Reactivar automatización",
  "ui.router": "Router",
  "ui.internet": "Internet",
  "ui.jitter": "Jitter",
  "ui.loss": "Pérdida",
  "ui.provisional": "(provisional)",
  "ui.late": "{n} respuestas tardías",
  "ui.wifi": "Wi-Fi",
  "ui.notConnected": "Sin Wi-Fi — monitor en pausa",
  "ui.channel": "canal {n}",
  "ui.phy": "PHY {n} Mbps",
  "ui.reconnect": "Reconectar Wi-Fi",
  "ui.reconnectConfirm": "El Wi-Fi se corta unos segundos. ¿Continuar?",
  "ui.reconnectBlocked": "No disponible con el modo silencio activo",
  "ui.reconnecting": "Reconectando…",
  "ui.reconnectDone": "Reconectado",
  "ui.events": "Cortes recientes",
  "ui.noEvents": "Sin cortes en la última hora",
  "ui.lastHour": "{n} en la última hora",
  "ui.test": "Quiet test",
  "ui.testStart": "Ejecutar quiet test (4 min)",
  "ui.testCancel": "Cancelar test",
  "ui.testRunning": "Bloque {n} de 4 · {cond}",
  "ui.testArming": "Preparando bloque {n} de 4…",
  "ui.testA": "referencia",
  "ui.testB": "modo silencio",
  "ui.testHint": "No uses AirDrop durante el test.",
  "ui.testResult": "Referencia: {a} picos >{ms} ms en {as} pings · Modo silencio: {b} en {bs}",
  "ui.testInvalid": "Test detenido: {reason}",
  "ui.testCancelled": "Test cancelado",
  "ui.settings": "Ajustes",
  "ui.quit": "Salir",
  "ui.privilegeMissing": "El modo silencio necesita un permiso (una sola vez).",
  "ui.installPrivilege": "Instalar permiso…",
  "ui.wardenDown": "El servicio en segundo plano no responde",
  "ui.recovering": "Restaurando el estado anterior…",
  "ui.probesBlocked": "Todos los pings fallan con el Wi-Fi activo. Un cortafuegos (LuLu, Little Snitch) puede estar bloqueando quietlink-helper.",
  "ui.paused": "Automatización en pausa",
  "ui.sessions": "Sesiones",
  "ui.noSessions": "Aún no hay sesiones",
  "ui.sessionLine": "{dur} min · p95 {p95} ms · {cuts} cortes · pérdida {loss} %",
  "set.title": "Ajustes de Quietlink",
  "set.triggers": "Disparadores",
  "set.monitor": "Monitor",
  "set.privileges": "Permisos",
  "set.data": "Datos",
  "set.about": "Acerca de",
  "set.presets": "Apps",
  "set.verified": "verificado",
  "set.unverified": "sin verificar",
  "set.showUnverified": "Mostrar presets sin verificar",
  "set.noVerified": "Aún no hay presets verificados en este Mac. Muestra los no verificados para verlos, o añade una app abierta.",
  "set.addApp": "Añadir app abierta…",
  "set.thisExe": "Solo este ejecutable",
  "set.wholeApp": "Toda la aplicación",
  "set.remove": "Quitar",
  "set.input": "Silenciar mientras un dispositivo de entrada esté activo",
  "set.inputHint": "Heurística: detecta llamadas en el navegador, pero cualquier app que use el micrófono — o unos cascos reproduciendo audio — puede activarlo.",
  "set.grace": "Margen tras terminar un disparador: {n} s",
  "set.external": "Destino externo de pings",
  "set.externalHint": "Pings continuos a este host (un tercero). Déjalo vacío para desactivarlo.",
  "set.extra": "Saltos extra (p. ej. nodos mesh), separados por comas",
  "set.menuPing": "Mostrar ping del router en la barra de menús",
  "set.explain": "Explicar cortes (experimental)",
  "set.explainHint": "Lee una parte acotada del log Wi-Fi del sistema para anotar escaneos o actividad AWDL cerca de un corte. Coincidencia, no causa.",
  "set.privStatus": "Estado",
  "set.privInstalled": "Instalado",
  "set.privMissing": "No instalado",
  "set.wardenRunning": "Servicio en segundo plano activo",
  "set.privExplain": "Quietlink instala una regla de sudoers que permite a tu cuenta ejecutar exactamente dos comandos sin contraseña: /sbin/ifconfig awdl0 down y /sbin/ifconfig awdl0 up. Cualquier proceso que se ejecute como tú también puede ejecutarlos. Un servicio en segundo plano (el warden) es la única parte de Quietlink que los ejecuta, y vuelve a activar AWDL si la app deja de responder.",
  "set.install": "Instalar",
  "set.uninstall": "Desinstalar",
  "set.retention": "Las muestras por segundo y los eventos se guardan 24 h; las sesiones, 30 días. Nada sale de este Mac salvo los pings.",
  "set.clear": "Borrar todos los datos",
  "set.cleared": "Borrado",
  "set.export": "Exportar diagnóstico",
  "set.includeIds": "Incluir identificadores (IPs, rutas)",
  "set.exported": "Guardado en {path}",
  "set.cli": "Instalar herramienta de línea de comandos",
  "set.cliDone": "Instalada en {path}",
  "set.login": "Abrir al iniciar sesión",
  "set.lang": "Idioma",
  "set.support": "Verificado en macOS 27 (Apple Silicon). Otras versiones pueden funcionar pero no están probadas.",
  "set.license": "Licencia MIT",
  "set.working": "Trabajando…",
  "set.failed": "Error: {error}",
  "ui.offNote": "AirDrop y Handoff funcionan con normalidad",
  "ui.quietFor": "Silenciar durante…",
  "ui.toRouter": "al router, últimos 5 min",
  "ui.factsLine": "{spikes} picos de más de {ms} ms · {lost} perdidos",
  "ui.cutOf": "Corte de {d}",
  "ui.pauseShort": "Pausar",
  "set.menuTraffic": "Mostrar bajada/subida actual en la barra de menús",
  "ui.traffic": "Tráfico",
};

export const strings: Record<Lang, Record<Key, string>> = { en, es };

export function t(lang: Lang, key: Key, vars: Record<string, string | number> = {}): string {
  return strings[lang][key].replace(/\{(\w+)\}/g, (m, name) => (name in vars ? String(vars[name]) : m));
}
